lsi: false
safe: true
theme: jekyll-theme-minimal
source: http://darleigh.github.io/site
include:
  - _include
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge